
# .github/workflows/format-check.yml
name: Code Format Check

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: silkeh/clang:21    # 修改为存在的版本
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format
        run: |
          find src -name '*.cpp' -o -name '*.h' -print0 | xargs -0 clang-format --dry-run --Werror